### ISSUE TITLE
Handling signed messages (smime.p7m attachments)

### ISSUE THREAD

**Issue by gasparez15** [bbottema/outlook-message-parser#4] opened 2018-11-29 10:03 UTC
Hi Benny,
I wanted to ask you if this library manages the signed Outlook message files.
Using the msgparser library I see that this message has an IPM.Note.SMIME class and that there is only one attachment called smime.p7m
This message has no body, but only an attachment
Is this library able to interpret the body and the attachments contained in the attachment smime?
[Outlook Signed Message.zip](https://github.com/bbottema/outlook-message-parser/files/2628563/Outlook.Signed.Message.zip)
Thanks 4 Y time
Alex

**Comment by bbottema** [comment] 2018-12-03 14:38
No, I'm not familiar with this and the underlying library used doesn't seem to do anything with it. I'll see what I can find out about it.

**Comment by bbottema** [comment] 2018-12-03 16:04
I've had success in reading this smime attachment and indeed found the content (which is just an .eml), but I'm unsure how to handle this scenario properly. If I open your supplied .eml in Thunderbird and that .msg in Outlook, both clients treat the attachment as the actual message. Is this behavior specified somewhere?

Currently I would be able to return the empty message with a MimeMultiPart.

**Comment by bbottema** [comment] 2018-12-03 16:36
In fact, since this is not actually Outlook specific (signed attachments), I'm going to move S/MIME support over to Simple Java Mail. That's because to support your particular case (signed MimeMessage), outlook-message-parser would have to add javax.mail and bouncy castle as new dependencies, which are rather heavy weight.

Simple Java Mail already has javax.mail and works with optional dependencies, of which bouncy castle can be one. More to the point, I wold like Simple Java Mail to allow new mails to be signed as well.

**Comment by gasparez15** [comment] 2018-12-03 17:57
Ok Benny,
in fact I agree with your reasoning, since the SMIME attachment is actually the real message (only encrypted) it probably makes more sense to read this message in your main library.
I hope that inside that you will provide a convenient method to decipher the message and extract the attachments
Thanks for your time
Alex

**Comment by bbottema** [comment] 2019-04-06 14:22
I thought of picking up this issue again and implement S/MIME in Simple Java Mail, but the same test I ran for this issue before stopped working erroring out with the following message:

>java.io.IOException: Invalid header signature; read 0xE011BDBFEFBDBFEF, expected 0xE11AB1A1E011CFD0

	at org.apache.poi.poifs.storage.HeaderBlock.<init>(HeaderBlock.java:140)
	at org.apache.poi.poifs.storage.HeaderBlock.<init>(HeaderBlock.java:104)
	at org.apache.poi.poifs.filesystem.POIFSFileSystem.<init>(POIFSFileSystem.java:138)
	at org.simplejavamail.outlookmessageparser.OutlookMessageParser.parseMsg(OutlookMessageParser.java:103)

That's so strange. Is there a time limit involved in S/MIME attachments? Outlook is not able to open the .msg anymore either... or did I edit the file somehow, I can't see since it isn't in git yet 🤔

**Comment by bbottema** [comment] 2019-04-11 19:43
@gasparez15, can you tell me how you obtained the .eml file you posted in that zip? It contains more data than I get from the .msg parser (specifically ID, replyTo and bounceTo addresses as well as a bunch of Outlook original headers):

![image](https://user-images.githubusercontent.com/2115718/55987905-d33da280-5ca2-11e9-95b0-2568cdca88f2.png)

**Comment by gasparez15** [comment] 2019-04-12 07:18
Hi Benny, that message was sent by Outlook (MS Office 2016) and received with Thunderbird. 
I saved it as an .eml file from Thunderbird

**Comment by gasparez15** [comment] 2019-04-12 07:28
This applies to the .eml file. 
About the .msg that has been saved by an application (outlook plugin) just before to be sent. 
To tell the truth, analyzing the situation now, I realized that maybe the .msg file is not fully complete, in fact opening it with Outlook, I didn't see the signature icon.
Now I have downloaded it again from Outlook (sent messages) and the other copy of the file has the signature icon instead.
I send you the two copies
[2copies-of-sent-message-outlook.zip](https://github.com/bbottema/outlook-message-parser/files/3072059/2copies-of-sent-message-outlook.zip)

**Comment by bbottema** [comment] 2019-04-12 10:37
Hmm, I was seeing the signature icon in Outlook365 though. I'll take a look at the new copy you included now, when I get home

**Comment by bbottema** [comment] 2019-04-12 20:14
> Hi Benny, that message was sent by Outlook (MS Office 2016) and received with Thunderbird.
> I saved it as an .eml file from Thunderbird

Aahhh, now I understand. Ok great, you helped me a lot with all this!

**Comment by bbottema** [comment] 2019-04-12 20:36
But I'm a little confused about how this works.

First of all, you signed and encrypted a message, but not with a public key I gave you. So how is it that I can decrypt this message without any key? It's all supposed to work with [keys](https://docs.ipswitch.com/moveit/central/onlineguide/en/MICSMIMEEmailOverview.htm) and [keystores and providers](https://github.com/markenwerk/java-utils-mail-smime), but I haven't added any of that yet.

Second thing is, The Outlook message is parsed as a plain content message with subject, FROM and TO details and an S/MIME signed attachment. Is the resulting email supposed to be a combination/merge  of the plain data and the decrypted message?

So:

- .msg
   - FROM name / address
   - TO names / addresses
   - SUBJECT
   - S/MIME signed attachment

Should result in the following?

- .msg
   - FROM name / address
   - TO names / addresses
   - SUBJECT
   - BODY taken from the decrypted attachment
   - attachments taken from the decrypted attachment

It's still confusing me a lot.

**Comment by gasparez15** [comment] 2019-04-13 08:20
Hi Benny, the message is signed but not encrypted
![Message-security](https://user-images.githubusercontent.com/28052369/56076841-b9e94300-5dd5-11e9-9e61-7f573af85017.png)

**Comment by bbottema** [comment] 2019-04-13 08:32
Hmm, the library I used reports it as encrypted, weird.

So what is the expected behavior then. I suppose I should reject the message unless there's a key available to verify the signature... otherwise what's the point of signing the message?

**Comment by bbottema** [comment] 2019-04-21 14:40
Hi @gasparez15, I finished implementation for reading .msg / .eml files in Simple Java Mail. Will be in the 6.0.0 release!

![image](https://user-images.githubusercontent.com/2115718/56471550-29090c00-6454-11e9-877d-50812bf7d522.png)

**Closed by bbottema** 2019-04-21 14:40 UTC
Labels: enhancement, need user input

**Comment by bbottema** [comment] 2019-04-22 13:48
I'm working on adding decryption now as well (only supports signed content currently). Are you able to provide me with additional examples?

I need the following:

1. signed (already have that one)
2. encrypted
3. signed, then encrypted
4. encrypted, then signed
5. some combination of multiple encryption/sign passes (should be rare in real world usage, but in theory this is possible and should be handled correctly as well)

For testing decryption, you would [need](https://docs.ipswitch.com/moveit/central/onlineguide/en/MICSMIMEEmailOverview.htm) to a generate private/public key pair, encrypt with the public key key and I would then need the private key to decrypt it.

**Comment by bbottema** [comment] 2019-04-23 18:46
Moo

1. [S_MIME test message signed.zip](https://github.com/bbottema/outlook-message-parser/files/3109099/S_MIME.test.message.signed.zip)
2. [S_MIME test message encrypted.zip](https://github.com/bbottema/outlook-message-parser/files/3109101/S_MIME.test.message.encrypted.zip)
3. [S_MIME test message encrypted_ then signed.zip](https://github.com/bbottema/outlook-message-parser/files/3109102/S_MIME.test.message.encrypted_.then.signed.zip)
4. [S_MIME test message encrypted_ then signed.zip](https://github.com/bbottema/outlook-message-parser/files/3109103/S_MIME.test.message.encrypted_.then.signed.zip)
5. Not sure what order to choose in addition to the above...

**Comment by bbottema** [comment] 2019-04-23 19:11
Ok, so that went all wrong apparently

**Comment by bbottema** [comment] 2019-04-23 19:46
I wasted many hours fooling around with self signed pkcs12 certificates in Outlook and Thunderbird, but it seems I have no clue what I'm doing :/

**Comment by bbottema** [comment] 2019-05-12 18:58
Got everything figured in the meantime... implemented both encrypted and/or signed messages. Implemented in Simple Java Mail, will be in the 6.0.0 release.

**Comment by bbottema** [comment] 2019-05-20 18:28
And now added signing / encrypting as well! Last step is to make sure it works from the command line as well and final documentation tweaks.
